version: "3.9"
services:
  api:
    build: ./backend
    ports:
      - "5200:5200"
  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5200/api}
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5200/api}
    ports:
      - "3000:3000"
    depends_on:
      - api
