export const countries = [
  "Andora",
  "Zjednoczone Emiraty Arabskie",
  "Afganistan",
  "Antigua i Barbuda",
  "Anguilla",
  "Albania",
  "Armenia",
  "Angola",
  "Antarktyda",
  "Argentyna",
  "Samoa Amerykańskie",
  "Austria",
  "Australia",
  "Aruba",
  "Wyspy Alandzkie",
  "Azerbejdżan",
  "Bośnia i Hercegowina",
  "Barbados",
  "Bangladesz",
  "Belgia",
  "Burkina Faso",
  "Bułgaria",
  "Bahrajn",
  "Burundi",
  "Benin",
  "Bermudy",
  "Brunei",
  "Boliwia",
  "Bonaire",
  "Brazylia",
  "Bahamy",
  "Bhutan",
  "Wyspy Bouveta",
  "Botswana",
  "Białoruś",
  "Belize",
  "Kanada",
  "Wyspy Kokosowe",
  "Demokratyczna Republika Konga",
  "Republika Środkowoafrykańska",
  "Kongo",
  "Szwajcaria",
  "Wybrzeże Kości Słoniowej",
  "Wyspy Cooka",
  "Chile",
  "Kamerun",
  "Chiny",
  "Kolumbia",
  "Kostaryka",
  "Kuba",
  "Wyspy Zielonego Przylądka",
  "Curacao",
  "Wyspa Bożego Narodzenia",
  "Cypr",
  "Czechy",
  "Niemcy",
  "Dżibuti",
  "Dania",
  "Dominika",
  "Dominikana",
  "Algieria",
  "Ekwador",
  "Estonia",
  "Egipt",
  "Sahara Zachodnia",
  "Erytrea",
  "Hiszpania",
  "Etiopia",
  "Finlandia",
  "Fidżi",
  "Falklandy",
  "Mikronezja",
  "Wyspy Owcze",
  "Francja",
  "Gabon",
  "Zjednoczone Królestwo",
  "Grenada",
  "Gruzja",
  "Gujana Francuska",
  "Ghana",
  "Gibraltar",
  "Grenlandia",
  "Gambia",
  "Gwinea",
  "Gwadelupa",
  "Gwinea Równikowa",
  "Grecja",
  "Georgia Południowa i Sandwich Południowy",
  "Gwatemala",
  "Guam",
  "Gwinea Bissau",
  "Gujana",
  "Hongkong",
  "Wyspy Heard i McDonalda",
  "Honduras",
  "Chorwacja",
  "Haiti",
  "Węgry",
  "Indonezja",
  "Irlandia",
  "Izrael",
  "Wyspa Man",
  "Indie",
  "Brytyjskie Terytorium Oceanu Indyjskiego",
  "Irak",
  "Iran",
  "Islandia",
  "Włochy",
  "Jersey",
  "Jamajka",
  "Jordania",
  "Japonia",
  "Kenia",
  "Kirgistan",
  "Kambodża",
  "Kiribati",
  "Komory",
  "Saint Kitts i Nevis",
  "Korea Północna",
  "Korea Południowa",
  "Kuwejt",
  "Kajmany",
  "Kazachstan",
  "Laotańska Republika Ludowo-Demokratyczna",
  "Liban",
  "Saint Lucia",
  "Liechtenstein",
  "Sri Lanka",
  "Liberia",
  "Lesotho",
  "Litwa",
  "Luksemburg",
  "Łotwa",
  "Arabia Libijska Dżamahirija",
  "Maroko",
  "Monako",
  "Mołdawia",
  "Czarnogóra",
  "Madagaskar",
  "Wyspy Marshalla",
  "Macedonia Północna",
  "Mali",
  "Mjanma",
  "Mongolia",
  "Makao",
  "Mariany Północne",
  "Martynika",
  "Mauretania",
  "Montserrat",
  "Malta",
  "Mauritius",
  "Malediwy",
  "Malawi",
  "Meksyk",
  "Malezja",
  "Mozambik",
  "Namibia",
  "Niger",
  "Wyspa Norfolk",
  "Nigeria",
  "Nikaragua",
  "Holandia",
  "Norwegia",
  "Nepal",
  "Nauru",
  "Niue",
  "Nowa Zelandia",
  "Oman",
  "Panama",
  "Peru",
  "Polinezja Francuska",
  "Papua Nowa Gwinea",
  "Filipiny",
  "Pakistan",
  "Polska",
  "Pitcairn",
  "Portoryko",
  "Palestyna",
  "Portugalia",
  "Palau",
  "Paragwaj",
  "Katar",
  "Rumunia",
  "Serbia",
  "Rosja",
  "Rwanda",
  "Arabia Saudyjska",
  "Wyspy Salomona",
  "Seszele",
  "Sudan",
  "Szwecja",
  "Singapur",
  "Wyspa Świętej Heleny",
  "Słowenia",
  "Słowacja",
  "Sierra Leone",
  "San Marino",
  "Senegal",
  "Somalia",
  "Surinam",
  "Południowy Sudan",
  "Wyspy Świętego Tomasza i Książęca",
  "Salwador",
  "Sint Maarten",
  "Syria",
  "Eswatini",
  "Wyspy Turks i Caicos",
  "Czad",
  "Togo",
  "Tajlandia",
  "Tadżykistan",
  "Tokelau",
  "Timor Wschodni",
  "Turkmenistan",
  "Tunezja",
  "Tonga",
  "Turcja",
  "Trynidad i Tobago",
  "Tuvalu",
  "Tajwan",
  "Tanzania",
  "Ukraina",
  "Uganda",
  "Stany Zjednoczone",
  "Urugwaj",
  "Uzbekistan",
  "Watykan",
  "Saint Vincent i Grenadyny",
  "Wenezuela",
  "Brytyjskie Wyspy Dziewicze",
  "Wyspy Dziewicze Stanów Zjednoczonych",
  "Wietnam",
  "Vanuatu",
  "Samoa",
  "Jemen",
  "Afryka Południowa",
  "Zambia",
  "Zimbabwe",
]
