-- Add new fields to Events table
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "InsurerClaimNumber" VARCHAR(100);
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "VehicleNumber" VARCHAR(100);
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "Brand" VARCHAR(100);
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "Model" VARCHAR(100);
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "Owner" VARCHAR(200);
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "InsuranceCompanyPhone" VARCHAR(50);
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "InsuranceCompanyEmail" VARCHAR(200);
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "PolicyNumber" VARCHAR(100);
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "ReportDateToInsurer" TIMESTAMP;
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "Liquidator" VARCHAR(200);
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "LeasingCompanyPhone" VARCHAR(50);
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "LeasingCompanyEmail" VARCHAR(200);
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "EventTime" VARCHAR(10);
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "Area" VARCHAR(50);
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "WereInjured" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "StatementWithPerpetrator" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Events" ADD COLUMN IF NOT EXISTS "PerpetratorFined" BOOLEAN DEFAULT FALSE;

-- Update Email table structure
ALTER TABLE "Emails" ADD COLUMN IF NOT EXISTS "BodyHtml" TEXT;
ALTER TABLE "Emails" ADD COLUMN IF NOT EXISTS "IsHtml" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Emails" ADD COLUMN IF NOT EXISTS "IsArchived" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Emails" ADD COLUMN IF NOT EXISTS "Direction" VARCHAR(50) DEFAULT 'Outbound';
ALTER TABLE "Emails" ADD COLUMN IF NOT EXISTS "Status" VARCHAR(50) DEFAULT 'Draft';
ALTER TABLE "Emails" ADD COLUMN IF NOT EXISTS "Tags" VARCHAR(500);
ALTER TABLE "Emails" ADD COLUMN IF NOT EXISTS "ClaimId" VARCHAR(50);
ALTER TABLE "Emails" ADD COLUMN IF NOT EXISTS "References" VARCHAR(500);
ALTER TABLE "Emails" ADD COLUMN IF NOT EXISTS "ReadAt" TIMESTAMP;
ALTER TABLE "Emails" ADD COLUMN IF NOT EXISTS "ErrorMessage" VARCHAR(2000);
ALTER TABLE "Emails" ADD COLUMN IF NOT EXISTS "RetryCount" INTEGER DEFAULT 0;

-- Rename email address columns for consistency
ALTER TABLE "Emails" RENAME COLUMN "FromAddress" TO "From";
ALTER TABLE "Emails" RENAME COLUMN "ToAddresses" TO "To";
ALTER TABLE "Emails" RENAME COLUMN "CcAddresses" TO "Cc";
ALTER TABLE "Emails" RENAME COLUMN "BccAddresses" TO "Bcc";

-- Update Document table
ALTER TABLE "Documents" RENAME COLUMN "FileType" TO "ContentType";
ALTER TABLE "Documents" ADD COLUMN IF NOT EXISTS "OriginalFileName" VARCHAR(255);
ALTER TABLE "Documents" ADD COLUMN IF NOT EXISTS "CloudUrl" VARCHAR(500);
ALTER TABLE "Documents" ADD COLUMN IF NOT EXISTS "FileUrl" VARCHAR(500);
ALTER TABLE "Documents" ADD COLUMN IF NOT EXISTS "Tags" VARCHAR(500);
ALTER TABLE "Documents" ADD COLUMN IF NOT EXISTS "IsPublic" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Documents" ADD COLUMN IF NOT EXISTS "FileHash" VARCHAR(64);
ALTER TABLE "Documents" ADD COLUMN IF NOT EXISTS "IsActive" BOOLEAN DEFAULT TRUE;

-- Update EmailAttachment table
ALTER TABLE "EmailAttachments" RENAME COLUMN "FileType" TO "ContentType";
ALTER TABLE "EmailAttachments" ADD COLUMN IF NOT EXISTS "ContentId" VARCHAR(100);
ALTER TABLE "EmailAttachments" ADD COLUMN IF NOT EXISTS "IsInline" BOOLEAN DEFAULT FALSE;
