-- Create clients table for the dictionary/lookup
CREATE TABLE IF NOT EXISTS clients (
    id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    name NVARCHAR(500) NOT NULL,
    full_name NVARCHAR(500) NOT NULL,
    short_name NVARCHAR(200),
    tax_id NVARCHAR(50),
    registration_number NVARCHAR(100),
    is_active BIT DEFAULT 1,
    created_at DATETIME2 DEFAULT GETDATE(),
    updated_at DATETIME2 DEFAULT GETDATE(),
    created_by NVARCHAR(200),
    updated_by NVARCHAR(200)
);

-- Create indexes for better performance
CREATE INDEX IX_clients_name ON clients(name);
CREATE INDEX IX_clients_full_name ON clients(full_name);
CREATE INDEX IX_clients_is_active ON clients(is_active);
CREATE INDEX IX_clients_created_at ON clients(created_at);

-- Insert sample client data based on the provided data
INSERT INTO clients (name, full_name, is_active) VALUES
('JPM GLOBAL OZIEWICZ STOBIŃKI WODZYŃSKI SP.JAWNA', 'JPM GLOBAL OZIEWICZ STOBIŃKI WODZYŃSKI SP.JAWNA', 1),
('KUROWSKI SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ', 'KUROWSKI SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ', 1),
('"MATRAK" M.A. ŁYCZKOWSCY SPÓŁKA JAWNA', '"MATRAK" M.A. ŁYCZKOWSCY SPÓŁKA JAWNA', 1),
('HTS LOGISTIC Sylwester Prus', 'HTS LOGISTIC Sylwester Prus', 1),
('WORLDTRANS SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ', 'WORLDTRANS SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ', 1),
('FINNEL Elżbieta Błażewicz', 'FINNEL Elżbieta Błażewicz', 1),
('SZAFRAN Paweł Szafrański', 'SZAFRAN Paweł Szafrański', 1),
('PWZ SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ', 'PWZ SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ', 1),
('D.P.TRANS DANIEL POCZYKOWSKI', 'D.P.TRANS DANIEL POCZYKOWSKI', 1),
('ZOFIA PISAREK', 'ZOFIA PISAREK', 1),
('PRZEDSIĘBIORSTWO HANDLOWO - USŁUGOWE "DER - TRANS"', 'PRZEDSIĘBIORSTWO HANDLOWO - USŁUGOWE "DER - TRANS" MARIUSZ DERLATKA, LIDIA DERLATKA, ŁUKASZ DERLATKA - SPÓŁKA JAWNA W ŚWIEBODZINIE', 1),
('CHARTER SP. Z O.O.', 'CHARTER SP. Z O.O.', 1),
('AGNIESZKA KĘDZIORA-URBANOWICZ JUST IN TIME SERVICE', 'AGNIESZKA KĘDZIORA-URBANOWICZ JUST IN TIME SERVICE AGNIESZKA KĘDZIORA-URBANOWICZ', 1),
('FIRMA TRANSPORTOWO-USŁUGOWA RODTRANS TOMASZ RODEWALD', 'FIRMA TRANSPORTOWO-USŁUGOWA RODTRANS TOMASZ RODEWALD', 1),
('EUROLOGISTIC TOMASZ WAC', 'EUROLOGISTIC TOMASZ WAC', 1),
('USŁUGI TRANSPORTOWE - PIĘTKA TOMASZ', 'USŁUGI TRANSPORTOWE - PIĘTKA TOMASZ', 1),
('TRANS-MAT ANNA WIŚNIEWSKA USŁUGI TRANSPORTOWE', 'TRANS-MAT ANNA WIŚNIEWSKA USŁUGI TRANSPORTOWE', 1),
('TOBER-MOTO MARCIN TOBER', 'TOBER-MOTO MARCIN TOBER', 1),
('PRZEDSIĘBIORSTWO HANDLOWO-USŁUGOWE FADO MARTYNA DROZDOWSKA', 'PRZEDSIĘBIORSTWO HANDLOWO-USŁUGOWE FADO MARTYNA DROZDOWSKA', 1),
('BYRSKI LOGISTIC SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ SPÓŁKA KOMANDYTOWA', 'BYRSKI LOGISTIC SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ SPÓŁKA KOMANDYTOWA', 1),
('RAFAŁ ZIĘBA TRANSPORT', 'RAFAŁ ZIĘBA TRANSPORT', 1),
('Przedsiebiorstwo Wielobranżowe ZNAJDEK Jadwiga Znajdek', 'Przedsiebiorstwo Wielobranżowe ZNAJDEK Jadwiga Znajdek', 1),
('AK-SPED SP. Z O.O.', 'AK-SPED SP. Z O.O.', 1),
('RGL ROBERT GAJEWSKI', 'RGL ROBERT GAJEWSKI', 1),
('DOLF-TRANS ANDRZEJ DAUKSZYS', 'DOLF-TRANS ANDRZEJ DAUKSZYS', 1),
('PMD GROUP SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ', 'PMD GROUP SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ', 1),
('PRZEDSIĘBIORSTWO HANDLOWO - USŁUGOWE Krause Wojciech', 'PRZEDSIĘBIORSTWO HANDLOWO - USŁUGOWE Krause Wojciech', 1),
('MPG-LOGISTIC SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ', 'MPG-LOGISTIC SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ', 1),
('ANNA KUKLA PHU', 'ANNA KUKLA PHU', 1),
('db insurance Dawid Bojarski', 'db insurance Dawid Bojarski', 1),
('"DAF-TRANS" SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ', '"DAF-TRANS" SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ', 1);

-- Add foreign key constraint to Events table to reference clients
ALTER TABLE Events ADD client_id UNIQUEIDENTIFIER;
ALTER TABLE Events ADD CONSTRAINT FK_Events_Clients FOREIGN KEY (client_id) REFERENCES clients(id);

-- Create index on the foreign key
CREATE INDEX IX_Events_client_id ON Events(client_id);
